name-template: "$RESOLVED_VERSION 🌈🐈"
tag-template: "$RESOLVED_VERSION"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  **Full changelog**: [`$PREVIOUS_TAG...$RESOLVED_VERSION`](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION)
