name: Lint Python

on:
  push:
    paths:
      - "update_pkg_deps/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: chartboost/ruff-action@v1
        with:
          config: .ruff.toml
