name: Python lint and fix

on:
  push:
    # paths:
    #   - "update_pkg_deps/**"

jobs:
  lint_and_fix:
    runs-on: python:3.12
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          args: --check .
          fix_args: --fix .
          config: .ruff.toml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style fixes by ruff"
