name: Status check

on: push

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Template manifest.json
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: manifest.json.j2
          output_file: manifest.json
          strict: true
          variables: |
            name=${{ github.event.repository.name }}
            version_number=${{ github.ref_name }}
            website_url=${{ github.server_url }}/${{ github.repository }}

      - name: Print manifest.json
        run: cat manifest.json
