name: Publish Mod

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Template manifest.json
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: manifest.json.j2
          output_file: manifest.json
          strict: true
          variables: |
            name=${{ github.event.repository.name }}
            version_number=${{ github.ref_name }}
            website_url=${{ github.server_url }}/${{ github.repository }}

      - name: Print manifest.json
        run: cat manifest.json

      - name: Upload Thunderstore package
        uses: GreenTF/upload-thunderstore-package@v4.2
        with:
          namespace: PapayaMods # the thunderstore 'team' to publish under
          description: Just a Lethal Company modpack
          token: ${{ secrets.THUNDERSTORE_API_TOKEN }}
          name: LethalLuna # the name of the package
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: lethal-company
          repo: northstar.thunderstore.io
          categories: | # <-- notice this pipe character
            modpacks,
            tools,
            audio,
            suits,
            emotes,
            serverside,
            clientside,
            misc
